// FIX: Replaced placeholder content with a valid question bank module to resolve import and syntax errors.
import { Difficulty, Question } from '../types';

export const subject = 'SAEB - Prova Brasil';
export const questions: Question[] = [
  // FÁCIL (Verde)
  {
    id: 25,
    difficulty: Difficulty.EASY,
    text: 'Na frase "O cachorro é rápido", qual palavra é o adjetivo?',
    options: { A: 'O', B: 'cachorro', C: 'é', D: 'rápido' },
    answer: 'D',
    explanation: '"Rápido" é um adjetivo que dá uma qualidade/característica ao substantivo "cachorro".'
  },
  {
    id: 26,
    difficulty: Difficulty.EASY,
    text: 'Se uma caixa tem 5 maçãs e você adiciona mais 7, com quantas maçãs você fica?',
    options: { A: '10', B: '11', C: '12', D: '13' },
    answer: 'C',
    explanation: 'A operação é uma simples adição: 5 + 7 = 12. Você terá 12 maçãs.'
  },
  {
    id: 31,
    difficulty: Difficulty.EASY,
    text: 'Uma pizza foi dividida em 5 fatias e Juca comeu 3. Qual fração representa a porção da pizza que foi consumida?',
    options: { A: '5/3', B: '3/5', C: '5/5', D: '3/2' },
    answer: 'B',
    explanation: 'A pizza foi dividida em 5 partes iguais e 3 foram consumidas, representando a fração 3/5.',
  },
  {
    id: 32,
    difficulty: Difficulty.EASY,
    text: 'Uma régua marca os números 0, 2, 4, 6, 8, 10, 12, e depois um "?". Seguindo o padrão, que número o "?" representa?',
    options: { A: '14', B: '13', C: '10', D: '16' },
    answer: 'A',
    explanation: 'A régua mostra uma sequência de números pares. O próximo número par depois de 12 é 14.',
  },
  {
    id: 33,
    difficulty: Difficulty.EASY,
    text: 'Anderson quer fazer um cubo para um jogo. Qual das opções de planificação a seguir ele deve usar para formar um cubo?',
    options: { A: 'Uma cruz com 5 quadrados', B: 'Uma fileira de 6 quadrados', C: 'Uma forma de "L" com 5 quadrados', D: 'Uma cruz com 4 quadrados na vertical e 2 nas laterais' },
    answer: 'D',
    explanation: 'A planificação que forma um cubo corretamente é a que parece uma cruz, com 4 quadrados em linha e um de cada lado do segundo quadrado.',
  },
  {
    id: 34,
    difficulty: Difficulty.EASY,
    text: 'Um polígono com seis lados é chamado de:',
    options: { A: 'Losango', B: 'Pentágono', C: 'Hexágono', D: 'Triângulo' },
    answer: 'C',
    explanation: 'Um polígono de 6 lados é, por definição, um hexágono.',
  },
  {
    id: 35,
    difficulty: Difficulty.EASY,
    text: 'Uma garagem precisa acomodar dois carros (1,70m de largura cada), com 0,50m entre eles e 0,30m de folga em cada lado. Qual a largura mínima da garagem?',
    options: { A: '3,40 m', B: '4,20 m', C: '4,50 m', D: '5,00 m' },
    answer: 'C',
    explanation: 'Soma total: 1,70 (carro) + 1,70 (carro) + 0,50 (espaço) + 0,30 (folga) + 0,30 (folga) = 4,50m.',
  },
  {
    id: 36,
    difficulty: Difficulty.EASY,
    text: 'Melissa é 1 hora mais velha que sua irmã gêmea. Quantos minutos ela é mais velha?',
    options: { A: '60 minutos', B: '60 horas', C: '60 segundos', D: '600 minutos' },
    answer: 'A',
    explanation: 'Uma hora é composta por 60 minutos.',
  },
  {
    id: 37,
    difficulty: Difficulty.EASY,
    text: 'Paula é 2 anos mais velha que Luana. Isso significa que Luana nasceu quantos meses depois de Paula?',
    options: { A: '24 meses', B: '12 meses', C: '48 meses', D: '96 meses' },
    answer: 'A',
    explanation: 'Cada ano tem 12 meses. Portanto, 2 anos equivalem a 2 x 12 = 24 meses.',
  },
  {
    id: 38,
    difficulty: Difficulty.EASY,
    text: 'José pagou seu carro em um financiamento de 60 meses. Isso equivale a quantos anos?',
    options: { A: '12 anos', B: '60 anos', C: '5 anos', D: '10 anos' },
    answer: 'C',
    explanation: 'Para converter meses em anos, divide-se por 12. Assim, 60 meses / 12 = 5 anos.',
  },
  {
    id: 39,
    difficulty: Difficulty.EASY,
    text: 'Um procedimento no cabeleireiro começou às 9h e durou 1 hora e 30 minutos. A que horas terminou?',
    options: { A: '10h', B: '11h', C: '10h 15min', D: '10h 30min' },
    answer: 'D',
    explanation: 'Somando 1h 30min a 9h00min, o resultado é 10h30min.',
  },
  {
    id: 40,
    difficulty: Difficulty.EASY,
    text: 'Júnior trocou dez moedas de R$0,50 e cinco moedas de R$1 por notas de R$5. Quantas notas ele recebeu?',
    options: { A: '3', B: '5', C: '2', D: '6' },
    answer: 'C',
    explanation: 'O total é (10 × 0,50) + (5 × 1) = 5 + 5 = R$10. Dividindo por 5, ele recebeu 2 notas.',
  },
  {
    id: 41,
    difficulty: Difficulty.EASY,
    text: 'Qual é a forma simplificada da fração 8/10?',
    options: { A: '4/5', B: '2/5', C: '2/2', D: '4/2' },
    answer: 'A',
    explanation: 'Dividindo o numerador e o denominador de 8/10 pelo maior divisor comum (2), obtemos 4/5.',
  },
  {
    id: 42,
    difficulty: Difficulty.EASY,
    text: 'Carlos comprou um computador de R$3.456,00 e uma impressora de R$1.234,00. Qual foi o total gasto?',
    options: { A: 'R$ 4.690,00', B: 'R$ 4.680,00', C: 'R$ 4.700,00', D: 'R$ 4.690,40' },
    answer: 'A',
    explanation: 'A soma dos valores é R$ 3.456,00 + R$ 1.234,00 = R$ 4.690,00.',
  },
  {
    id: 43,
    difficulty: Difficulty.EASY,
    text: 'No número 482.739, qual é o valor posicional do algarismo 8?',
    options: { A: '800.000', B: '80.000', C: '800', D: '8.000' },
    answer: 'B',
    explanation: 'O algarismo 8 está na casa da dezena de milhar, representando o valor de 80.000.',
  },
  {
    id: 44,
    difficulty: Difficulty.EASY,
    text: 'Qual das opções mostra a decomposição correta do número 326.419?',
    options: { A: '300.000+20.000+6.000+400+10+9', B: '3.000.000+...', C: '30.000+...', D: '300.000+...+900' },
    answer: 'A',
    explanation: 'A decomposição correta é a soma dos valores de cada algarismo: (3×100.000)+(2×10.000)+(6×1.000)+(4×100)+(1×10)+(9×1).',
  },
  {
    id: 45,
    difficulty: Difficulty.EASY,
    text: 'Um parque recebeu 12.345 visitantes por dia durante 7 dias. Qual o total de visitantes no período?',
    options: { A: '85.415', B: '86.415.000', C: '86.415', D: '87.415' },
    answer: 'C',
    explanation: 'O total de visitantes é 12.345 × 7 = 86.415.',
  },
  {
    id: 46,
    difficulty: Difficulty.EASY,
    text: 'Se 4.800 maçãs foram distribuídas igualmente entre 10 turmas, quantas maçãs cada turma recebeu?',
    options: { A: '2.400', B: '1.600', C: '480', D: '1.200' },
    answer: 'C',
    explanation: 'A divisão de 4.800 maçãs por 10 turmas resulta em 480 maçãs para cada uma.',
  },
  {
    id: 47,
    difficulty: Difficulty.EASY,
    text: 'De uma pizza de 8 fatias, 3 foram comidas. Qual fração representa a parte que restou?',
    options: { A: '3/5', B: '3/8', C: '5/5', D: '5/8' },
    answer: 'D',
    explanation: 'Restaram 8 - 3 = 5 fatias. A fração correspondente é 5/8.',
  },
  {
    id: 48,
    difficulty: Difficulty.EASY,
    text: 'Júlia comeu 3/6 de um bolo e Pedro comeu 1/2. Comparando as quantidades, pode-se afirmar que:',
    options: { A: 'Júlia comeu mais', B: 'Pedro comeu mais', C: 'Ambos comeram a mesma quantidade', D: 'Não é possível saber' },
    answer: 'C',
    explanation: 'A fração 3/6 é equivalente a 1/2, pois ao simplificar 3/6 (dividindo ambos por 3) obtemos 1/2.',
  },
  {
    id: 49,
    difficulty: Difficulty.EASY,
    text: 'Quantas bandejas para 30 ovos são necessárias para embalar 600 ovos?',
    options: { A: '30', B: '20', C: '10', D: '5' },
    answer: 'B',
    explanation: 'Para encontrar o número de bandejas, divide-se o total de ovos pela capacidade da bandeja: 600 / 30 = 20.',
  },
  {
    id: 50,
    difficulty: Difficulty.EASY,
    text: 'Quantos pesos de 500 gramas são necessários para equilibrar um peso de 2 kg em uma balança?',
    options: { A: '2', B: '4', C: '5', D: '8' },
    answer: 'B',
    explanation: '2 kg equivalem a 2000 gramas. Como cada peso tem 500 gramas, são necessários 2000 / 500 = 4 pesos.',
  },
  {
    id: 51,
    difficulty: Difficulty.EASY,
    text: 'Paulo deposita R$10,00 por semana em seu cofrinho. Quanto ele terá em 10 semanas?',
    options: { A: 'R$ 50,00', B: 'R$ 150,00', C: 'R$ 100,00', D: 'R$ 80,00' },
    answer: 'C',
    explanation: 'O total será o valor semanal multiplicado pelo número de semanas: 10 × R$ 10,00 = R$ 100,00.',
  },
  {
    id: 52,
    difficulty: Difficulty.EASY,
    text: 'Em qual dos seguintes números o algarismo "3" ocupa a casa das dezenas: 523, 390, 232, 213?',
    options: { A: '523', B: '390', C: '232', D: '213' },
    answer: 'C',
    explanation: 'No número 232, o algarismo 3 está na segunda posição da direita para a esquerda, que corresponde à casa das dezenas.',
  },
  {
    id: 53,
    difficulty: Difficulty.EASY,
    text: 'Uma padaria produziu 600 panetones e os acondicionou em caixas com 12 unidades cada. Quantas caixas foram necessárias?',
    options: { A: '500', B: '50', C: '20', D: '10' },
    answer: 'B',
    explanation: 'Dividindo o total de panetones pela capacidade de cada caixa, temos 600 / 12 = 50 caixas.',
  },
  {
    id: 54,
    difficulty: Difficulty.EASY,
    text: 'Para comprar uma calça online, Gabi precisa medir a cintura. Qual instrumento ela deve usar?',
    options: { A: 'Relógio', B: 'Balança', C: 'Termômetro', D: 'Fita métrica' },
    answer: 'D',
    explanation: 'A fita métrica é o instrumento ideal para medir circunferências do corpo, como a da cintura.',
  },
  {
    id: 55,
    difficulty: Difficulty.EASY,
    text: 'Uma foto de 30cm por 17cm é ampliada, dobrando suas dimensões. Quais serão o novo comprimento e largura?',
    options: { A: '17cm e 15cm', B: '90cm e 51cm', C: '30cm e 24cm', D: '60cm e 34cm' },
    answer: 'D',
    explanation: 'Dobrando as dimensões, o novo comprimento será 30cm × 2 = 60cm, e a nova largura será 17cm × 2 = 34cm.',
  },

  // MÉDIO (Amarelo)
  {
    id: 27,
    difficulty: Difficulty.MEDIUM,
    text: 'Qual é a figura de linguagem presente na frase "Choveram elogios para o artista"?',
    options: { A: 'Metáfora', B: 'Hipérbole', C: 'Eufemismo', D: 'Ironia' },
    answer: 'B',
    explanation: 'Hipérbole é uma figura de linguagem que representa um exagero intencional. Dizer que "choveram elogios" é uma forma exagerada de dizer que foram muitos elogios.'
  },
  {
    id: 28,
    difficulty: Difficulty.MEDIUM,
    text: 'Um retângulo tem 8 cm de comprimento e 5 cm de largura. Qual é a sua área?',
    options: { A: '13 cm²', B: '26 cm²', C: '40 cm²', D: '35 cm²' },
    answer: 'C',
    explanation: 'A área de um retângulo é calculada multiplicando-se o comprimento pela largura. Portanto, 8 cm * 5 cm = 40 cm².'
  },

  // DIFÍCIL (Vermelho)
  {
    id: 29,
    difficulty: Difficulty.HARD,
    text: 'Leia o trecho: "A menina, que era muito estudiosa, passou no vestibular." A oração "que era muito estudiosa" é classificada como:',
    options: { A: 'Oração Subordinada Adjetiva Restritiva', B: 'Oração Subordinada Adjetiva Explicativa', C: 'Oração Coordenada Sindética Explicativa', D: 'Oração Subordinada Substantiva Objetiva Direta' },
    answer: 'B',
    explanation: 'A oração está entre vírgulas e adiciona uma informação extra sobre o substantivo "menina", mas não restringe seu sentido. Portanto, é uma oração subordinada adjetiva explicativa.'
  },
  {
    id: 30,
    difficulty: Difficulty.HARD,
    text: 'Se o preço de um produto aumentou 20% e depois diminuiu 20%, qual foi a alteração percentual em relação ao preço original?',
    options: { A: 'Nenhuma alteração', B: 'Aumentou 4%', C: 'Diminuiu 4%', D: 'Diminuiu 10%' },
    answer: 'C',
    explanation: 'Suponha um preço original de R$100. Com aumento de 20%, vai para R$120. Uma diminuição de 20% sobre R$120 é R$24 (120 * 0.20). O novo preço é R$120 - R$24 = R$96. Em relação ao preço original de R$100, houve uma diminuição de 4%.'
  }
];